// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Island: typeof import('./node_modules/.pnpm/iles@0.8.7/node_modules/iles/dist/client/app/components/Island.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagYoutube: typeof import('./src/components/TagYoutube.svelte')['default']
    WebcamOnline: typeof import('./src/components/WebcamOnline.svelte')['default']
  }
}
